name: Build

on:
  push:
    tags:
      - 'v*'
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: BungeeChatSync - ${{ steps.get_version.outputs.version }}
          body: |
            Build ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
  
  build:
    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package
      
      - uses: actions/upload-artifact@v1
        name: Action-Upload
        with:
          name: Release
          path: target

      - uses: AButler/upload-release-assets@v2.0
        name: Upload Release File
        with:
          files: target/ChatSync-${{ steps.get_version.outputs.version-without-v }}.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.get_version.outputs.version }}